### ISSUE TITLE
预训练完后执行python sft.py报错找不到文件

### ISSUE THREAD

**Issue by xamofb-xsk** [DLLXW/baby-llama2-chinese#11]
FileNotFoundError: [Errno 2] No such file or directory: './data/sft_data.csv'

**Comment by DLLXW** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: './data/sft_data.csv'

这个是需要自己制作的SFT数据，网上有很多的哈，自行下载处理

**Comment by Vincent-ZHQ** [comment]
#28
