### ISSUE TITLE
百度云垃圾

### ISSUE THREAD

**Issue by KKIverson** [DLLXW/baby-llama2-chinese#14]
墙裂建议把百度云换成阿里云的分享，百度云限速太严重了。恶心。。。

**Comment by DLLXW** [comment]
> 墙裂建议把百度云换成阿里云的分享，百度云限速太严重了。恶心。。。

开个会员，贼快哈哈哈

**Comment by downeykking** [comment]
可以用huggingface上的 https://huggingface.co/datasets/xuqinyang/BaiduBaike-5.63M/tree/main
