### ISSUE TITLE
没有找到medical_qa_144w

### ISSUE THREAD

**Issue by Yuiceee** [DLLXW/baby-llama2-chinese#2]
其他的预训练和用于微调的数据都找到了，但是没有“medical_qa_144w.csv”，请问这部分数据在哪里呢？

**Comment by DLLXW** [comment]
> 这部分是https://huggingface.co/datasets/shibing624/medical/tree/main/finetune这里的数据转成的csv格式。README.md里面也给了哈，可以自行处理，也不一定非要转csv的

**Comment by Deep1994** [comment]
> 



> > 这部分是[https://huggingface.co/datasets/shibing624/medical/tree/main/finetune这里的数据转成的csv格式。README.md里面也给了哈，可以自行处理，也不一定非要转csv的](https://huggingface.co/datasets/shibing624/medical/tree/main/finetune%E8%BF%99%E9%87%8C%E7%9A%84%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%88%90%E7%9A%84csv%E6%A0%BC%E5%BC%8F%E3%80%82README.md%E9%87%8C%E9%9D%A2%E4%B9%9F%E7%BB%99%E4%BA%86%E5%93%88%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E8%A1%8C%E5%A4%84%E7%90%86%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%B8%80%E5%AE%9A%E9%9D%9E%E8%A6%81%E8%BD%ACcsv%E7%9A%84)

这部分数据也是用来预训练的是吧，也就是说，预训练出来的模型其实已经具备一定的医学问答的能力了？能不能预训练的时候不用这部分数据，在sft的时候使用，这跟预训练就一起训练有什么区别吗？哪种方式下的模型的医学问答能力更强？

**Comment by Deep1994** [comment]
> > 这部分是[https://huggingface.co/datasets/shibing624/medical/tree/main/finetune这里的数据转成的csv格式。README.md里面也给了哈，可以自行处理，也不一定非要转csv的](https://huggingface.co/datasets/shibing624/medical/tree/main/finetune%E8%BF%99%E9%87%8C%E7%9A%84%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%88%90%E7%9A%84csv%E6%A0%BC%E5%BC%8F%E3%80%82README.md%E9%87%8C%E9%9D%A2%E4%B9%9F%E7%BB%99%E4%BA%86%E5%93%88%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E8%A1%8C%E5%A4%84%E7%90%86%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%B8%80%E5%AE%9A%E9%9D%9E%E8%A6%81%E8%BD%ACcsv%E7%9A%84)

在公司下不了百度网盘，https://huggingface.co/datasets/TigerResearch/pretrain_zh，这个数据如果想拿来替代百度百科数据进行预训练的话，该怎么使用呢？我看里面都是.parquet格式的数据，但是，貌似可以直接通过datasets.load_dataset('TigerResearch/pretrain_zh')导入，这样的数据怎么接入你的代码呢？

**Comment by DLLXW** [comment]
> 

如果想要模型在某一专有领域表现好，预训练里面也肯定是加得越多相关领域的语料，SFT后模型的效果越好。

tiger数据是.parquet格式，可以用专门的python包读取，很简单的，自己百度一下即可。读出来也是类似csv的表格吧。然后再参考data_process.py里面几个例子对它进行分词存为.bin即可。估计总共代码不会超过30行，你照着data_process.py自己写下

**Comment by DLLXW** [comment]
> > > 这部分是[https://huggingface.co/datasets/shibing624/medical/tree/main/finetune这里的数据转成的csv格式。README.md里面也给了哈，可以自行处理，也不一定非要转csv的](https://huggingface.co/datasets/shibing624/medical/tree/main/finetune%E8%BF%99%E9%87%8C%E7%9A%84%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%88%90%E7%9A%84csv%E6%A0%BC%E5%BC%8F%E3%80%82README.md%E9%87%8C%E9%9D%A2%E4%B9%9F%E7%BB%99%E4%BA%86%E5%93%88%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E8%A1%8C%E5%A4%84%E7%90%86%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%B8%80%E5%AE%9A%E9%9D%9E%E8%A6%81%E8%BD%ACcsv%E7%9A%84)
> 
> 在公司下不了百度网盘，[https://huggingface.co/datasets/TigerResearch/pretrain_zh，这个数据如果想拿来替代百度百科数据进行预训练的话，该怎么使用呢？我看里面都是.parquet格式的数据，但是，貌似可以直接通过datasets.load_dataset('TigerResearch/pretrain_zh')导入，这样的数据怎么接入你的代码呢？](https://huggingface.co/datasets/TigerResearch/pretrain_zh%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%95%B0%E6%8D%AE%E5%A6%82%E6%9E%9C%E6%83%B3%E6%8B%BF%E6%9D%A5%E6%9B%BF%E4%BB%A3%E7%99%BE%E5%BA%A6%E7%99%BE%E7%A7%91%E6%95%B0%E6%8D%AE%E8%BF%9B%E8%A1%8C%E9%A2%84%E8%AE%AD%E7%BB%83%E7%9A%84%E8%AF%9D%EF%BC%8C%E8%AF%A5%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%91%A2%EF%BC%9F%E6%88%91%E7%9C%8B%E9%87%8C%E9%9D%A2%E9%83%BD%E6%98%AF.parquet%E6%A0%BC%E5%BC%8F%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BD%86%E6%98%AF%EF%BC%8C%E8%B2%8C%E4%BC%BC%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E9%80%9A%E8%BF%87datasets.load_dataset('TigerResearch/pretrain_zh')%E5%AF%BC%E5%85%A5%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%9A%84%E6%95%B0%E6%8D%AE%E6%80%8E%E4%B9%88%E6%8E%A5%E5%85%A5%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E5%91%A2%EF%BC%9F)

你可以在个人电脑下载，再传到公司电脑？
