### ISSUE TITLE
eos token是空字符串

### ISSUE THREAD

**Issue by Destiny-Lu** [DLLXW/baby-llama2-chinese#38]
查看数据处理脚本时发现文本中没有eos token。试验发现，eos的token id是2，但是tokenizer.decode([2])是空字符串，不清楚是什么问题。

**Comment by jh01231230** [comment]
如果用decode方法解码，返回结果应该是把所有特殊字符都去掉了。

**Comment by Destiny-Lu** [comment]
@jh01231230 我加了skip special token = False 也不行，我看tokenizer里的decode源码也没有特殊处理直接调用了sentencepiece库

**Comment by jh01231230** [comment]
@Destiny-Lu 直接用encode()调用的是transformers.PreTrainedTokenizer的实现，在这个类eos_id的定义用的是ChatGLMTokenizer().eos_token_id，赋值是来自SPTokenizer。但用的时候则是直接调用来自SPTokenizer的ChatGLMTokenizer().special_tokens['<eos>']。但这样反复横跳的调用就很混乱。这里用SPTokenizer实现PreTrainedTokenizer的部分应该需要改一改，有点乱。

然后是为什么decode()不返回特殊字符，大概是因为decode()调用了convert_ids_to_tokens()。这个方法里调用了被改写的_convert_id_to_token()方法，这个方法调用了SPTokenizer里定义的convert_id_to_token()方法。这么一大串以后你可以看源码逻辑是碰到特殊字符都返回空，那自然就被去掉了。

我们可以自定义一下convert_id_to_token方法，当index为self.eos_id的时候，返回一个自定义的eos_token。或者可以在ChatGLMTokenizer()里面改_convert_id_to_token()方法，这里的eos_token已经定义好了，更加方便。

**Comment by Destiny-Lu** [comment]
明白了，谢谢！
