### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by AI-Study-Han** [DLLXW/baby-llama2-chinese#47]
确定训练出的模型可以完成基本的回答吗？为什么我训练的模型都是乱说。https://github.com/AI-Study-Han/Mini-Llama2-Chinese

**Comment by AI-Study-Han** [comment]
能给个训练好的测试一下吗？

**Comment by DLLXW** [comment]
> 能给个训练好的测试一下吗？

加下我微信：qq2257164884

**Comment by DLLXW** [comment]
> 确定训练出的模型可以完成基本的回答吗？为什么我训练的模型都是乱说。https://github.com/AI-Study-Han/Mini-Llama2-Chinese

https://github.com/DLLXW/baby-llama2-chinese/issues/50

应该是这个原因
