### ISSUE TITLE
请教下参数大小如何计算

### ISSUE THREAD

**Issue by CanvaChen** [DLLXW/baby-llama2-chinese#5]
README.md中提到50M参数的配置为：
max_seq_len = 512
dim = 512
n_layers = 8
n_heads = 8

请问如何计算参数大小？

**Comment by DLLXW** [comment]
> README.md中提到50M参数的配置为： max_seq_len = 512 dim = 512 n_layers = 8 n_heads = 8
> 
> 请问如何计算参数大小？

model.py里面有计算param这部分哈，仔细看下。
