### ISSUE TITLE
跑训练报错

### ISSUE THREAD

**Issue by singeleaf** [DLLXW/baby-llama2-chinese#58]
执行命令
torchrun --standalone --nproc_per_node=1 pretrain.py

错误信息

> master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
> [2024-01-24 15:07:20,199][distributed_c10d.py][INFO] Added key: store_based_barrier_key:1 to store for rank: 0
> [2024-01-24 15:07:20,199][distributed_c10d.py][INFO] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
> device: cuda:0
> tokens per iteration will be: 16,384
> breaks down as: 1 grad accum steps * 1 processes * 32 batch size * 512 max seq len
> memmap:True train data.shape:(266249, 512)
> downloading finished.....
> Initializing a new model from scratch
> num decayed parameter tensors: 57, with 58,470,912 parameters
> num non-decayed parameter tensors: 17, with 8,704 parameters
> using fused AdamW: True
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 1299143) of binary: /root/miniconda3/envs/pretrain/bin/python
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/pretrain/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/root/miniconda3/envs/pretrain/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/pretrain/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/root/miniconda3/envs/pretrain/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/root/miniconda3/envs/pretrain/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/pretrain/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =========================================================
> pretrain.py FAILED
> ---------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ---------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-01-24_15:07:23
>   rank      : 0 (local_rank: 0)
>   exitcode  : -11 (pid: 1299143)
>   error_file: <N/A>
>   traceback : Signal 11 (SIGSEGV) received by PID 1299143
> =========================================================

**Comment by yuanpinz** [comment]
我也是

**Comment by HildaM** [comment]
请问你现在解决了吗？我也遇到了/(ㄒoㄒ)/~~

**Comment by DLLXW** [comment]
加qq群
