### ISSUE TITLE
请问单卡16G显存的4060Ti能训练吗？

### ISSUE THREAD

**Issue by XiaoluJiayou** [DLLXW/baby-llama2-chinese#64]
money有限，只有单卡请16G显存的4060Ti，但是也想从头训练或者微调一下大语言模型，了解一下从分词到训练再到最后测试的这么一个过程。请问大佬有没有什么建议

**Comment by DLLXW** [comment]
> money有限，只有单卡请16G显存的4060Ti，但是也想从头训练或者微调一下大语言模型，了解一下从分词到训练再到最后测试的这么一个过程。请问大佬有没有什么建议

可以跑起来代码，但batch会很小，训练很慢。所以可以用作学习，但是很难训练出智能
