### ISSUE TITLE
c4-zh数据有问题

### ISSUE THREAD

**Issue by yasohasakii** [DLLXW/baby-llama2-chinese#67]
网盘上的数据缺失了两个（三部分加起来只有94个，缺失了28和75），下载后用tar解压.jsonl.zst文件提示错误

**Comment by maoxiangyi** [comment]
确实缺两个文件

**Comment by yasohasakii** [comment]
> zst文件解压，需要用zstd解压 yum install zstd unzstd file.zst

好的，谢谢！
