### ISSUE TITLE
交个作业吧

### ISSUE THREAD

**Issue by yasohasakii** [DLLXW/baby-llama2-chinese#70]
预训练的eval，怎么说呢。。。
![image](https://github.com/DLLXW/baby-llama2-chinese/assets/20236150/23b8e003-d26b-4447-b135-bbbd2b13f79d)

**Comment by zs1314** [comment]
![Image](https://github.com/user-attachments/assets/340281cf-26e1-465b-b70a-d5a4d4de6a13)
加1
